#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_api_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: fedora-21
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-21-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: debian-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: debian-7-0-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-15.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-15-04-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
  #
  # mysql2_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-5.8'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'ubuntu-10.04'
    ]

  - name: client55-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6.5',
      'fedora-20',
      'debian-7.0',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      #'debian-7.0',
      #'centos-6.5',
      #'centos-7.0',
      'fedora-20',
      #'ubuntu-12.04',
      'ubuntu-14.04'
    ]
